name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          template: classic
          filename: profile-header.svg
          base: activity, community, repositories
          config_timezone: Asia/Jakarta
          config_twemoji: yes
      
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: habits.svg
          base: "" # Disables default blocks
          config_timezone: Asia/Jakarta
          config_twemoji: yes
          plugin_habits: yes
          plugin_habits_charts: yes
          plugin_habits_charts_type: classic
          plugin_habits_days: 14
          plugin_habits_facts: yes
          plugin_habits_from: 200
          plugin_habits_languages_limit: 8
          plugin_habits_languages_threshold: 0%

      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: isocalendar.svg
          base: "" # Disables default blocks
          config_timezone: Asia/Jakarta
          config_twemoji: yes
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year

      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: metrics-languages.svg
          base: "" # Disables the default avatar/header block
          config_timezone: Asia/Jakarta
          config_twemoji: yes
          plugin_languages: yes
          plugin_languages_analysis_timeout: 15
          plugin_languages_analysis_timeout_repositories: 7.5
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages_limit: 8
          plugin_languages_recent_categories: markup, programming
          plugin_languages_recent_days: 14
          plugin_languages_recent_load: 300 
          plugin_languages_sections: most-used
          plugin_languages_threshold: 0%

      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: metrics-achievements.svg
          base: "" # Disables default blocks
          config_timezone: Asia/Jakarta
          config_twemoji: yes
          plugin_achievements: yes
          plugin_achievements_display: compact
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: C

      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: metrics-lines.svg
          base: "" # Disables default blocks
          config_timezone: Asia/Jakarta
          config_twemoji: yes
          plugin_lines: yes
          plugin_lines_history_limit: 1
          plugin_lines_repositories_limit: 4
          plugin_lines_sections: base